CREATE OR REPLACE FUNCTION CalculateAge(p_dob DATE)
RETURN NUMBER
IS
  v_age NUMBER;
BEGIN
  v_age := FLOOR(MONTHS_BETWEEN(SYSDATE, p_dob) / 12);
  RETURN v_age;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('Age: ' || CalculateAge(TO_DATE('2000-06-10', 'YYYY-MM-DD')));
END;
/
