CREATE TABLE customers (
    customer_id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    balance NUMBER,
    LastModified DATE
);

CREATE TABLE transactions (
    txn_id NUMBER PRIMARY KEY,
    customer_id NUMBER,
    txn_date DATE,
    amount NUMBER,
    txn_type VARCHAR2(50)
);

CREATE TABLE auditlog (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    txn_id NUMBER,
    customer_id NUMBER,
    log_time DATE,
    action VARCHAR2(50)
);

INSERT INTO customers VALUES (101, 'Siri', 'siri56@mail.com', 5600, SYSDATE);
INSERT INTO customers VALUES (102, 'Raji', 'raji12@mail.com', 3500, SYSDATE);


CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON transactions
FOR EACH ROW
BEGIN
    INSERT INTO auditlog(txn_id, customer_id, log_time, action)
    VALUES (:NEW.txn_id, :NEW.customer_id, SYSDATE, 'Transaction Added');
END;
/


BEGIN
    INSERT INTO transactions VALUES (1, 101, SYSDATE, 1000, 'Deposit');
    DBMS_OUTPUT.PUT_LINE('Audit Log:');
    FOR rec IN (SELECT txn_id, customer_id, action, log_time FROM auditlog) LOOP
        DBMS_OUTPUT.PUT_LINE('Txn ID: ' || rec.txn_id || ' | Customer ID: ' || rec.customer_id || 
                             ' | Action: ' || rec.action || ' | Time: ' || TO_CHAR(rec.log_time, 'DD-MON-YYYY HH:MI:SS'));
    END LOOP;
END;
/

